title: RapidQandA
description: RapidQandA — the fastest way to create your quizzes and lessons from plain old text.
logo: /assets/images/logo/bordered_logo_128.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
plugins:
  - jekyll-relative-links
