title: Text2Lesson
description: Text2Lesson — the fastest way to create your lessons from plain old text.
logo: /assets/images/bordered_logo_128.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
